export type TIconType =
      | "menu"
      | "clear"
      | "facebook"
      | "instagram"
      | "linkedin"
      | "calender"
      | "location"
      | "clock"
      | "share"
      | "parking"
      | "accommodation"
      | "arrow-right"
      | "arrow-left"
      | "lock"
      | "unlock";
